name: next-sandbox

on: [push]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_kEY_V }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRETS_V }} 
  
jobs:
  build:
    name: Project Next
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/setup-node@v3
    
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
     
    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # install the python version needed
    
       
    - name: Install dependencies
      run: |
        apt-get update && apt-get install -y wget tar
        wget https://github.com/tfsec/tfsec/releases/download/v1.28.1/tfsec-linux-amd64
        chmod +x tfsec-linux-amd64
        mv tfsec-linux-amd64 /usr/local/bin/tfsec
        wget https://github.com/terraform-linters/tflint/releases/download/v0.30.0/tflint_linux_amd64.zip
        unzip tflint_linux_amd64.zip
        mv tflint /usr/local/bin/tflint
        wget https://github.com/tmccombs/hcl2json/releases/download/v0.5.0/hcl2json_linux_amd64
        chmod +x hcl2json_linux_amd64
        mv hcl2json_linux_amd64 /usr/local/bin/hcl2json
    
    - name: Terraform format
      id: format
      run: terraform fmt
       
    - name: Run tfsec
      run: tfsec .

    - name: Terraform init
      id: init
      run: terraform init -reconfigure -backend=false
    
    - name: Terraform validate
      id: validate
      run: terraform validate

    - name: Terraform plan
      id: plan
      run: terraform plan -out=tfplan

    - name: Terraform show
      id: show
      run: terraform show -json ./tfplan > tfplan.json

    




